USE[AirStack]
GO

/****** Object:  Table [dbo].[Item]    Script Date: 09.12.2022 12:05:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Item] (

    [ID][bigint] IDENTITY(1, 1) NOT NULL,

    [Code] [nvarchar] (300) NOT NULL,

    [ParentCode] [nvarchar] (300) NULL,
 CONSTRAINT[PK_Item] PRIMARY KEY CLUSTERED 
(

    [ID] ASC
)WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON[PRIMARY]
) ON[PRIMARY]
GO